In [91]:
import torch
import numpy 
from torchvision.io import read_image, ImageReadMode
from drive_agent import *
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
agenetNetwork = AgentNNetwork()

In [3]:
img = torch.ones([4,3,240,320])
s = torch.rand((4,1))
v = torch.rand((4,2))

In [5]:
action = agenetNetwork(img, s, v)

In [6]:
action

tensor([[0.4786, 0.4607],
        [0.4785, 0.4609],
        [0.4786, 0.4609],
        [0.4784, 0.4610]], grad_fn=<SigmoidBackward0>)

In [6]:
i = 0
for name, param in p_encoder.named_parameters():
    if param.requires_grad == True:
        print("NO.", i, name)
        i += 1

NO. 0 resnet.conv1.weight
NO. 1 resnet.bn1.weight
NO. 2 resnet.bn1.bias
NO. 3 resnet.layer1.0.conv1.weight
NO. 4 resnet.layer1.0.bn1.weight
NO. 5 resnet.layer1.0.bn1.bias
NO. 6 resnet.layer1.0.conv2.weight
NO. 7 resnet.layer1.0.bn2.weight
NO. 8 resnet.layer1.0.bn2.bias
NO. 9 resnet.layer1.1.conv1.weight
NO. 10 resnet.layer1.1.bn1.weight
NO. 11 resnet.layer1.1.bn1.bias
NO. 12 resnet.layer1.1.conv2.weight
NO. 13 resnet.layer1.1.bn2.weight
NO. 14 resnet.layer1.1.bn2.bias
NO. 15 resnet.layer2.0.conv1.weight
NO. 16 resnet.layer2.0.bn1.weight
NO. 17 resnet.layer2.0.bn1.bias
NO. 18 resnet.layer2.0.conv2.weight
NO. 19 resnet.layer2.0.bn2.weight
NO. 20 resnet.layer2.0.bn2.bias
NO. 21 resnet.layer2.0.downsample.0.weight
NO. 22 resnet.layer2.0.downsample.1.weight
NO. 23 resnet.layer2.0.downsample.1.bias
NO. 24 resnet.layer2.1.conv1.weight
NO. 25 resnet.layer2.1.bn1.weight
NO. 26 resnet.layer2.1.bn1.bias
NO. 27 resnet.layer2.1.conv2.weight
NO. 28 resnet.layer2.1.bn2.weight
NO. 29 resnet.layer2.1.b

In [ ]:
a = torch.randint(0,9,(5,10))
b = torch.randint(0,9,(5,5))

In [12]:
c = torch.cat((a,b), dim = 1)

In [75]:
gamma = 1.0
def compute_return(rewards): 
    Returns = [0]
    for i in range(len(rewards)-1, -1, -1): 
        print(rewards[i] + gamma * Returns[-1])
        Returns.append(rewards[i] + gamma * Returns[-1])
    Returns.reverse()
    return Returns[:-1]

In [80]:
N = 5
rewards = [i for i in range(1, N+1)]

In [81]:
rewards

[1, 2, 3, 4, 5]

In [82]:
compute_return(rewards)

5.0
9.0
12.0
14.0
15.0


[15.0, 14.0, 12.0, 9.0, 5.0]

In [73]:
a 

In [85]:
env_state = [True, False, True, False, False] 

In [ ]:
ids = torch.tensor([i for i in range(len(env_state)) if env_state[i]]).to(device)

In [93]:
ids

tensor([0, 2])

In [ ]:
if ids.isEmpty():
    print("Yes")

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [95]:
v = [[1,2,3], [4], [7,2]]

In [97]:
v[1] = []

In [98]:
v

[[1, 2, 3], [], [7, 2]]

In [115]:
u = torch.tensor([0 for _ in range(5)]).to(device).reshape(5,1)
v = torch.tensor([5 for _ in range(5)]).to(device).reshape(5,1)

In [131]:
u = torch.cat([u,v], dim = 1)
print(u)

tensor([[0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]], device='cuda:0')


In [ ]:
u[4] = torch.tensor([0]).to(device)

TypeError: 'module' object is not callable

In [134]:
u[4]

tensor([0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], device='cuda:0')